CREATE TABLE IF NOT EXISTS users (
 id VARCHAR(64) PRIMARY KEY,
 username VARCHAR(64) NOT NULL UNIQUE,
 email VARCHAR(320) NOT NULL UNIQUE,
 password_hash TEXT NOT NULL,
 role VARCHAR(32) NOT NULL DEFAULT 'user',
 disabled BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS sessions (
 id VARCHAR(128) PRIMARY KEY,
 user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 expires_at TIMESTAMPTZ NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS nodes (
 id VARCHAR(64) PRIMARY KEY,
 name VARCHAR(128) NOT NULL,
 hostname VARCHAR(255),
 address VARCHAR(255) NOT NULL,
 status VARCHAR(32) NOT NULL DEFAULT 'offline',
 maintenance BOOLEAN NOT NULL DEFAULT FALSE,
 daemon_version VARCHAR(64),
 os VARCHAR(128),
 architecture VARCHAR(64),
 cpu_total BIGINT NOT NULL DEFAULT 0,
 cpu_used BIGINT NOT NULL DEFAULT 0,
 memory_total BIGINT NOT NULL DEFAULT 0,
 memory_used BIGINT NOT NULL DEFAULT 0,
 disk_total BIGINT NOT NULL DEFAULT 0,
 disk_used BIGINT NOT NULL DEFAULT 0,
 last_heartbeat TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS node_credentials (
 node_id VARCHAR(64) PRIMARY KEY REFERENCES nodes(id) ON DELETE CASCADE,
 secret_hash TEXT NOT NULL,
 rotated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS servers (
 id VARCHAR(64) PRIMARY KEY,
 owner_id VARCHAR(64) NOT NULL REFERENCES users(id),
 node_id VARCHAR(64) NOT NULL REFERENCES nodes(id),
 name VARCHAR(128) NOT NULL,
 description TEXT NOT NULL DEFAULT '',
 status VARCHAR(32) NOT NULL DEFAULT 'stopped',
 runtime VARCHAR(32) NOT NULL DEFAULT 'docker',
 minecraft_version VARCHAR(64),
 server_type VARCHAR(32),
 memory_mb BIGINT NOT NULL DEFAULT 1024,
 cpu_percent BIGINT NOT NULL DEFAULT 100,
 disk_mb BIGINT NOT NULL DEFAULT 10240,
 root_path TEXT NOT NULL,
 suspended BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS allocations (
 id VARCHAR(64) PRIMARY KEY,
 node_id VARCHAR(64) NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
 server_id VARCHAR(64) REFERENCES servers(id) ON DELETE SET NULL,
 ip INET NOT NULL,
 port INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
 UNIQUE(node_id, ip, port)
);
CREATE TABLE IF NOT EXISTS subusers (
 server_id VARCHAR(64) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
 user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 permissions JSONB NOT NULL DEFAULT '[]',
 PRIMARY KEY(server_id, user_id)
);
CREATE TABLE IF NOT EXISTS backups (
 id VARCHAR(64) PRIMARY KEY,
 server_id VARCHAR(64) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
 path TEXT NOT NULL,
 size_bytes BIGINT NOT NULL DEFAULT 0,
 status VARCHAR(32) NOT NULL DEFAULT 'pending',
 checksum VARCHAR(128),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS api_keys (
 id VARCHAR(64) PRIMARY KEY,
 user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 name VARCHAR(128) NOT NULL,
 secret_hash TEXT NOT NULL,
 scopes JSONB NOT NULL DEFAULT '[]',
 expires_at TIMESTAMPTZ,
 last_used_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGSERIAL PRIMARY KEY,
 actor_id VARCHAR(64) REFERENCES users(id) ON DELETE SET NULL,
 action VARCHAR(128) NOT NULL,
 target_type VARCHAR(64) NOT NULL,
 target_id VARCHAR(128),
 result VARCHAR(32) NOT NULL,
 request_id VARCHAR(128),
 ip INET,
 metadata JSONB NOT NULL DEFAULT '{}',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS notifications (
 id VARCHAR(64) PRIMARY KEY,
 user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 type VARCHAR(64) NOT NULL,
 title VARCHAR(255) NOT NULL,
 message TEXT NOT NULL,
 dedupe_key VARCHAR(255),
 read_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS server_transfers (
 id VARCHAR(64) PRIMARY KEY,
 server_id VARCHAR(64) NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
 source_node_id VARCHAR(64) NOT NULL,
 destination_node_id VARCHAR(64) NOT NULL,
 status VARCHAR(32) NOT NULL DEFAULT 'pending',
 error TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 completed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_servers_owner ON servers(owner_id);
CREATE INDEX IF NOT EXISTS idx_servers_node ON servers(node_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor_created ON audit_logs(actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications(user_id, created_at DESC);
