import { Request, Response } from "express";
import axios from "axios";
import { readJSON, writeJSON } from "../services/db.js";
import { createServerContainer, startContainer, stopContainer, restartContainer, deleteContainer, getContainerStatus, sendContainerCommand, attachContainerSocket, getContainerStats, SUPPORTED_JAVA_VERSIONS, defaultDocker } from "../services/docker.js";
import { createSftpUser, deleteSftpUser } from "../services/sftp.js";
import crypto from "crypto";
import fs from "fs-extra";
import path from "path";
import { ZipArchive } from "archiver";
import extract from "extract-zip";
import {nodeControl} from "../services/nodeClient.js";
import {nodeConnection} from "../services/nodeEndpoint.js";
import {audit} from "../services/security.js";
import { copyDirectorySafely, extractZipSafely } from "../services/archiveSafety.js";


const remoteForServer=async(server:any)=>{
 if(!server?.nodeId||server.nodeId==="local") return null;
 const nodes=await readJSON("nodes.json")||[]; const n=nodes.find((x:any)=>x.id===server.nodeId);
 if(!n) throw new Error("Node not found");
 if(n.disabled) throw new Error("Node is disabled");
 return nodeConnection(n);
};

const nodeStatusForServer=(node:any)=>{
 if(!node) return null;
 if(node.maintenance) return "MAINTENANCE";
 if(node.installing) return "INSTALLING";
 if(node.error) return "ERROR";
 if(node.disabled) return "DISABLED";
 if(node.isLocal && !node.credentialHash) return "SETUP_REQUIRED";
 const heartbeat=node.lastHeartbeat?Date.parse(node.lastHeartbeat):NaN;
 return Number.isFinite(heartbeat) && Date.now()-heartbeat<=45_000 ? "ONLINE" : "OFFLINE";
};

const canManageServer = (req: Request, server: any) => {
  const user = (req as any).user;
  return user?.role === "admin" || user?.role === "owner" || server?.owner === user?.id;
};
const serverBasePath = (serverId: string) => path.resolve(process.cwd(), ".data", "servers", serverId);
const resolveServerPath = (serverId: string, requestedPath: unknown) => {
  const base = serverBasePath(serverId);
  // The file manager uses POSIX-style paths such as "/" and "/server.properties".
  // path.resolve(base, "/...") treats those as host-absolute paths, which makes
  // the root listing fail and can break every file operation. Normalize to a
  // server-relative path before resolving, then enforce the workspace boundary.
  const relativePath = String(requestedPath || "").replace(/\\/g, "/").replace(/^\/+/, "");
  const target = path.resolve(base, relativePath || ".");
  return target === base || target.startsWith(`${base}${path.sep}`) ? target : null;
};
const backupBasePath = (serverId: string) => path.resolve(process.cwd(), ".data", "backups", serverId);
const resolveBackupPath = (serverId: string, requestedPath: unknown) => {
  const base = backupBasePath(serverId);
  const target = path.resolve(base, String(requestedPath || ""));
  return target === base || target.startsWith(`${base}${path.sep}`) ? target : null;
};

const ensureLocalWorkspaceFiles = async (server: any) => {
  if (!server?.containerId || String(server.nodeId || "local") !== "local") return;
  const serverDir = path.join(process.cwd(), ".data", "servers", String(server.id));
  await fs.ensureDir(serverDir);
  const propertiesPath = path.join(serverDir, "server.properties");
  if (!(await fs.pathExists(propertiesPath))) {
    await fs.writeFile(propertiesPath, [
      `server-port=${server.port || 25565}`,
      "motd=A Minecraft Server",
      "online-mode=true",
      "pvp=true",
      "difficulty=easy",
      "gamemode=survival",
      "max-players=20",
      "view-distance=10",
      "allow-flight=false",
      "enable-command-block=false",
      "hardcore=false",
      "",
    ].join("\n"));
  }
  const eulaPath = path.join(serverDir, "eula.txt");
  if (!(await fs.pathExists(eulaPath))) await fs.writeFile(eulaPath, "# Generated by Snck\neula=true\n");
};

const nodeOperationError = (error: any, fallback: string) => {
  const dockerUnavailable = error?.dockerUnavailable === true || error?.responseData?.dockerUnavailable === true;
  const nodeUnavailable = error?.nodeUnavailable === true;
  const timeout = error?.timeout === true;
  const authFailed = error?.authFailed === true || Number(error?.statusCode) === 401;
  const responseInvalid = error?.nodeResponseInvalid === true;
  const message = String(error?.message || error?.responseData?.error || fallback);
  const statusCode = Number(error?.statusCode || (dockerUnavailable || nodeUnavailable ? 503 : 500));
  const safeStatus = authFailed ? 502 : (responseInvalid ? 502 : ((dockerUnavailable || nodeUnavailable || timeout) ? 503 : (statusCode >= 400 && statusCode < 600 ? statusCode : 500)));
  const body: any = dockerUnavailable ? { error: message, dockerUnavailable: true } : { error: message };
  if (authFailed) {
    body.nodeAuthenticationFailed = true;
    body.hint = "The daemon rejected the node credential. Reconnect or rotate the node credential, then reinstall the node configuration if necessary.";
  } else if (responseInvalid) {
    body.nodeResponseInvalid = true;
    body.hint = "The endpoint responded, but it is not a ShiroNex daemon response. Check the FQDN route, Cloudflare Access policy, tunnel ingress, and daemon version.";
  } else if (timeout) {
    body.nodeUnavailable = nodeUnavailable;
    body.timeout = true;
    body.hint = "The node or Cloudflare proxy did not complete the request in time. Confirm the daemon is running, then check the FQDN, Cloudflare Tunnel/Zero Trust ingress, daemon port, firewall, and image-pull connectivity. Initial Minecraft image pulls may take several minutes.";
  } else if (nodeUnavailable) {
    body.nodeUnavailable = true;
    body.timeout = false;
    body.hint = "Verify the node FQDN, DNS, Cloudflare Tunnel or Zero Trust ingress, TLS mode, daemon port, and firewall before retrying.";
  }
  return { statusCode: safeStatus, body };
};

export const getServers = async (req: Request, res: Response) => {
  const user = (req as any).user;
  const servers = await readJSON("servers.json") || [];
  
  // Filter for normal users
  const userServers = user.role === "admin" || user.role === "owner" ? servers : servers.filter((s: any) => s.owner === user.id);

  // Update statuses
  const [usersData, nodesData] = await Promise.all([readJSON("users.json"), readJSON("nodes.json")]);
  const users = usersData || [];
  const nodes = nodesData || [];
  const updatedServers = await Promise.all(userServers.map(async (server: any) => {
    const next = { ...server };
    if (server.containerId) {
      try {
        const status = await getContainerStatus(server.containerId, server.nodeId);
        next.status = status?.State?.Running ? "online" : "offline";
      } catch (error: any) {
        // A single unreachable node must not blank the whole fleet view.
        next.status = "offline";
        next.nodeUnavailable = error?.nodeUnavailable === true;
        next.nodeError = error?.message || "Node status is temporarily unavailable.";
      }
    }
    const ownerRecord = users.find((candidate: any) => candidate.id === server.owner);
    const nodeRecord = nodes.find((candidate: any) => candidate.id === (server.nodeId || "local"));
    return {
      ...next,
      nodeId: server.nodeId || "local",
      nodeName: nodeRecord?.name || (server.nodeId === "local" ? "Local Node" : "Unknown node"),
      nodeStatus: nodeStatusForServer(nodeRecord),
      ownerUsername: ownerRecord?.username || server.owner || "Unassigned",
      address: `${server.ipAlias || nodeRecord?.publicIp || nodeRecord?.hostname || "127.0.0.1"}:${server.port || "—"}`,
      lastActivity: server.updatedAt || server.lastActivity || server.createdAt || null,
      playersOnline: server.playersOnline ?? null,
      playersMax: server.playersMax ?? null,
    };
  }));

  res.json(updatedServers);
};

export const getServer = async (req: Request, res: Response) => {
  const { id } = req.params;
  const user = (req as any).user;
  const servers = await readJSON("servers.json") || [];
  const server = servers.find((s: any) => s.id === id);
  if (!server) {
    res.status(404).json({ error: "Server not found" });
    return;
  }
  if (user.role !== "admin" && user.role !== "owner" && server.owner !== user.id) {
    return res.status(403).json({ error: "Forbidden" });
  }

  try {
    const status = await getContainerStatus(server.containerId, server.nodeId);
    server.status = status?.State?.Running ? "online" : "offline";
  } catch (error: any) {
    server.status = "offline";
    server.nodeUnavailable = error?.nodeUnavailable === true;
    server.nodeError = error?.message || "Node status is temporarily unavailable.";
  }
  res.json(server);
};

export const getServerStats = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const user = (req as any).user;
    const servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    if (!server) {
      res.status(404).json({ error: "Server not found" });
      return;
    }
    if (user.role !== "admin" && user.role !== "owner" && server.owner !== user.id) {
      return res.status(403).json({ error: "Forbidden" });
    }

    const limitRamBytes = server.ram ? Number(server.ram) * 1024 * 1024 * 1024 : null;
    const limitDiskBytes = server.disk ? Number(server.disk) * 1024 * 1024 * 1024 : null;
    if (server.containerId) {
      const stats = await getContainerStats(server.containerId, server.nodeId);
      res.json({
        ...stats,
        timestamp: stats?.timestamp ?? Date.now(),
        limitRamBytes,
        limitDiskBytes,
        limitCpu: server.cpu ? Number(server.cpu) : null,
        // Legacy fields remain for older clients; new clients use the byte fields above.
        limitRam: server.ram ? Number(server.ram) * 1024 : null,
        limitDisk: server.disk ? Number(server.disk) : null,
      });
    } else {
      res.json({
        available: false,
        timestamp: Date.now(),
        cpu: null,
        ram: null,
        disk: null,
        networkRxBytes: null,
        networkTxBytes: null,
        limitRamBytes,
        limitDiskBytes,
        limitCpu: server.cpu ? Number(server.cpu) : null,
        limitRam: server.ram ? Number(server.ram) * 1024 : null,
        limitDisk: server.disk ? Number(server.disk) : null,
      });
    }
  } catch (err: any) {
    const failure = nodeOperationError(err, "Unable to read server telemetry");
    res.status(failure.statusCode).json({ ...failure.body, available: false, timestamp: Date.now() });
  }
};

export const createServer = async (req: Request, res: Response) => {
  const user = (req as any).user;
  const isStaff = user.role === "admin" || user.role === "owner";
  const { name, ram, port, version, theme, cpu, disk, owner, ipAlias, type, nodeId, allocationId, javaVersion, lifetimeHours } = req.body;
  const settings = await readJSON("settings.json") || {};
  const free = settings.freeService || { enabled: false, ram: 2, cpu: 100, disk: 5, maxServers: 1, durationHours: 168 };
  if (!isStaff && !free.enabled) return res.status(403).json({ error: "Free server creation is currently disabled by the Owner." });
  const existingServers = await readJSON("servers.json") || [];
  let expiresAt: string | null = null;
  if (!isStaff) {
    const owned = existingServers.filter((s:any) => s.owner === user.id);
    if (owned.length >= Number(free.maxServers || 1)) return res.status(403).json({ error: `Free plan allows at most ${Number(free.maxServers || 1)} server(s) per user.` });
    if (Number(ram) > Number(free.ram) || Number(cpu || 100) > Number(free.cpu) || Number(disk || 10) > Number(free.disk)) {
      return res.status(403).json({ error: `Free plan limits: ${free.ram} GB RAM, ${free.cpu}% CPU, ${free.disk} GB disk.` });
    }
  }
  const useServiceDefault = lifetimeHours === "default";
  const requestedLifetime = lifetimeHours === "" || lifetimeHours === undefined || lifetimeHours === null || useServiceDefault ? null : Number(lifetimeHours);
  if (requestedLifetime !== null && (!Number.isFinite(requestedLifetime) || requestedLifetime < 1 || requestedLifetime > 87600)) return res.status(400).json({ error: "Lifetime must be blank for permanent or between 1 and 87600 hours." });
  const effectiveLifetime = useServiceDefault && !isStaff ? Number(free.durationHours || 0) : requestedLifetime;
  if (effectiveLifetime !== null && effectiveLifetime > 0) expiresAt = new Date(Date.now() + effectiveLifetime * 3600000).toISOString();
  const normalizedJavaVersion = javaVersion ? String(javaVersion) : "";
  if (normalizedJavaVersion && !SUPPORTED_JAVA_VERSIONS.includes(normalizedJavaVersion as typeof SUPPORTED_JAVA_VERSIONS[number])) {
    return res.status(400).json({ error: `Unsupported Java version. Choose one of: ${SUPPORTED_JAVA_VERSIONS.join(", ")}` });
  }
  if (!name || !ram || !port) {
    res.status(400).json({ error: "Missing required fields (name, ram, port)" });
    return;
  }
  const serverPort = Number(port);
  if (!Number.isInteger(serverPort) || serverPort < 1 || serverPort > 65535) {
    return res.status(400).json({ error: "Server port must be an integer from 1 to 65535." });
  }

  const requestedNodeId = String(nodeId || "");
  if (!requestedNodeId) return res.status(400).json({ error: "Select a node before creating a server." });
  const nodes = await readJSON("nodes.json") || [];
  const selectedNode = nodes.find((node: any) => node.id === requestedNodeId);
  if (!selectedNode) return res.status(400).json({ error: "Node not found" });
  if (!isStaff && selectedNode.freeServiceLocked) return res.status(403).json({ error: "This node is locked for Free Minecraft Service. Choose another available node." });
  if (selectedNode.disabled) return res.status(409).json({ error: "Selected node is disabled" });
  if (selectedNode.maintenance) return res.status(409).json({ error: "Selected node is in maintenance mode; new server creation is blocked" });
  if (selectedNode.isLocal) {
    // Local nodes are managed directly through the panel host Docker socket. They
    // do not need a remote daemon heartbeat or nodeConnection() preflight.
    try {
      await defaultDocker.ping();
      selectedNode.localReady = true;
      selectedNode.lastHeartbeat = new Date().toISOString();
      selectedNode.error = null;
      await writeJSON("nodes.json", nodes);
    } catch (err: any) {
      return res.status(503).json({
        error: "The local Docker runtime is unavailable.",
        dockerUnavailable: true,
        details: String(err?.message || err),
        hint: "Start Docker Engine and ensure the panel process can access /var/run/docker.sock."
      });
    }
  } else {
    const heartbeat = selectedNode.lastHeartbeat ? Date.parse(selectedNode.lastHeartbeat) : NaN;
    const heartbeatTimeout = Math.max(30000, Number(process.env.NODE_HEARTBEAT_TIMEOUT_MS || 45000));
    if (!Number.isFinite(heartbeat) || Date.now() - heartbeat > heartbeatTimeout) return res.status(409).json({ error: "Selected node is offline. Install the daemon and wait for an authenticated heartbeat before deploying." });

    // ONLINE means the daemon can reach the panel. Preflight the reverse direction
    // as well, because Cloudflare Tunnel/FQDN ingress can fail independently.
    try {
      await nodeControl.health(nodeConnection(selectedNode));
    } catch (err: any) {
    const failure = nodeOperationError(err, "The selected node could not be reached.");
    return res.status(failure.statusCode).json({
      ...failure.body,
      nodeUnavailable: err?.nodeUnavailable === true,
      timeout: err?.timeout === true,
      nodeResponseInvalid: err?.nodeResponseInvalid === true,
      hint: failure.body?.hint || "Verify the node FQDN, Cloudflare Tunnel or Zero Trust ingress, TLS mode, daemon port, and firewall before retrying.",
      });
    }
  }

  const users = await readJSON("users.json") || [];
  const requestedOwner = isStaff && owner ? String(owner) : String(user.id);
  if (!users.some((candidate: any) => candidate.id === requestedOwner)) return res.status(400).json({ error: "Selected server owner was not found" });

  const allocations = await readJSON("allocations.json") || [];
  let selectedAllocation:any = null;
  if (allocationId) {
    selectedAllocation = allocations.find((a:any)=>a.id===String(allocationId) && String(a.nodeId)===requestedNodeId && !a.assignedServerId);
    if (!selectedAllocation) return res.status(409).json({ error: "Allocation is unavailable or belongs to another node." });
    if (serverPort < Number(selectedAllocation.portStart) || serverPort > Number(selectedAllocation.portEnd)) return res.status(400).json({ error: "Server port is outside the selected allocation." });
  } else {
    return res.status(400).json({ error: "An available allocation is required for every node." });
  }
  const id = crypto.randomUUID();
  const serverData = {
    id,
    name,
    owner: requestedOwner,
    ram,
    cpu: cpu || 100,
    disk: disk || 10,
    port: serverPort,
    ipAlias: ipAlias || "",
    nodeId: requestedNodeId,
    type: type || "PAPER",
    version: version || "1.21.1",
    javaVersion: normalizedJavaVersion || "",
    theme: theme || "default",
    status: "installing",
    createdAt: new Date().toISOString(),
    expiresAt,
    containerId: null as string | null,
  };

  const servers = await readJSON("servers.json") || [];
  
  if (servers.find((s: any) => String(s.nodeId || "local") === requestedNodeId && Number(s.port) === serverPort)) {
    res.status(400).json({ error: "Port is already in use on the selected node." });
    return;
  }

  servers.push(serverData);
  await writeJSON("servers.json", servers);
  if (selectedAllocation) { selectedAllocation.assignedServerId = id; await writeJSON("allocations.json", allocations); }

  try {
    const containerId = await createServerContainer(serverData);
    serverData.containerId = containerId;
    serverData.status = "offline";
    await writeJSON("servers.json", Object.assign(servers, servers.map((s:any)=>s.id===id?serverData:s)));
    await createSftpUser(id).catch(e => console.error("SFTP user creation failed:", e));
    await audit("server.created",req,{serverId:id,nodeId:serverData.nodeId});
    res.json(serverData);
  } catch (err: any) {
    console.error(err);
    if (selectedAllocation) { selectedAllocation.assignedServerId = null; await writeJSON("allocations.json", allocations); }
    const current = await readJSON("servers.json") || []; await writeJSON("servers.json", current.filter((x:any)=>x.id!==id));
    const failure = nodeOperationError(err, "Failed to create the server on the selected node.");
    res.status(failure.statusCode).json({
      ...failure.body,
      nodeUnavailable: err?.nodeUnavailable === true,
      timeout: err?.timeout === true,
      nodeResponseInvalid: err?.nodeResponseInvalid === true,
      hint: failure.body?.hint || "Verify the node FQDN, Cloudflare Tunnel or Zero Trust ingress, TLS mode, daemon port, and firewall before retrying.",
    });
  }
};

export const updateOwner = async (req: Request, res: Response) => {
  const user = (req as any).user;
  if (user.role !== "admin" && user.role !== "owner") {
    return res.status(403).json({ error: "Only admins can update owner" });
  }

  const { id } = req.params;
  const { owner } = req.body;

  if (!owner) return res.status(400).json({ error: "Owner required" });

  const servers = await readJSON("servers.json") || [];
  const server = servers.find((s: any) => s.id === id);

  if (!server) return res.status(404).json({ error: "Server not found" });

  server.owner = owner;
  await writeJSON("servers.json", servers);
  
  res.json({ success: true });
};

export const updateIpAlias = async (req: Request, res: Response) => {
  const user = (req as any).user;
  const { id } = req.params;
  const { ipAlias } = req.body;

  const servers = await readJSON("servers.json") || [];
  const server = servers.find((s: any) => s.id === id);

  if (!server) return res.status(404).json({ error: "Server not found" });

  if (user.role !== "admin" && user.role !== "owner" && server.owner !== user.id) {
    return res.status(403).json({ error: "Forbidden" });
  }

  server.ipAlias = ipAlias;
  await writeJSON("servers.json", servers);
  
  res.json({ success: true });
};

export const deleteServer = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const user = (req as any).user;
    
    let servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    
    if (!server) {
      return res.status(404).json({ error: "Server not found" });
    }

    if (user.role !== "admin" && user.role !== "owner") {
      return res.status(403).json({ error: "Only admins can delete servers" });
    }

    if (server.containerId) {
      await deleteContainer(server.containerId, server.nodeId);
    }
    
    servers = servers.filter((s: any) => s.id !== id);
    await writeJSON("servers.json", servers);

    const allocations = await readJSON("allocations.json") || [];
    let allocationChanged = false;
    for (const allocation of allocations) {
      if (allocation.assignedServerId === id) {
        allocation.assignedServerId = null;
        allocationChanged = true;
      }
    }
    if (allocationChanged) await writeJSON("allocations.json", allocations);
    
    // Remove files
    const serverDir = path.join(process.cwd(), ".data", "servers", id);
    try {
      await fs.remove(serverDir);
    } catch (e) {
      console.error("Failed to remove server directory", e);
    }
    
    await deleteSftpUser(id).catch(e => console.error("SFTP user deletion failed:", e));
    
    await audit("server.deleted",req,{serverId:id,nodeId:server.nodeId});
    res.json({ success: true });
  } catch (err: any) {
    console.error(err);
    res.status(500).json({ error: err.message });
  }
};

export const startServer = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const servers = await readJSON("servers.json") || [];
    
    const server = servers.find((s: any) => s.id === id);
    if (!server || !server.containerId) {
      return res.status(404).json({ error: "Not found" });
    }
    if (!canManageServer(req, server)) return res.status(403).json({ error: "Forbidden" });
    if (server.suspended) {
      return res.status(403).json({ error: "Server is suspended" });
    }

    try {
      const io = req.app.get("io");
      if (io) io.to(`server_${id}`).emit("clear_logs");
      
      await startContainer(server.containerId, server.nodeId);
    } catch (startErr: any) {
      if (startErr.statusCode === 404 || (startErr.message && startErr.message.toLowerCase().includes("no such container"))) {
        console.log(`Container missing for server ${server.id}. Recreating...`);
        server.containerId = await createServerContainer(server);
        await writeJSON("servers.json", servers);
        await startContainer(server.containerId, server.nodeId);
      } else {
        throw startErr;
      }
    }
    await attachContainerSocket(server.containerId, server.id, server.nodeId);
    await audit("server.started",req,{serverId:id,nodeId:server.nodeId});
    res.json({ success: true });
  } catch (err: any) {
    console.error("Start server error:", err);
    const failure = nodeOperationError(err, "Failed to start server");
    res.status(failure.statusCode).json(failure.body);
  }
};

export const stopServer = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    if (!server || !server.containerId) {
      return res.status(404).json({ error: "Not found" });
    }
    if (!canManageServer(req, server)) return res.status(403).json({ error: "Forbidden" });
    try {
      await stopContainer(server.containerId, server.nodeId);
    } catch (stopErr: any) {
      if (stopErr.statusCode === 404 || (stopErr.message && stopErr.message.toLowerCase().includes("no such container"))) {
        console.log(`Container already missing for server ${server.id}. Assuming stopped.`);
      } else {
        throw stopErr;
      }
    }
    await audit("server.stopped",req,{serverId:id,nodeId:server.nodeId});
    res.json({ success: true });
  } catch (err: any) {
    console.error("Stop server error:", err);
    const failure = nodeOperationError(err, "Failed to stop server");
    res.status(failure.statusCode).json(failure.body);
  }
};

export const restartServer = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    if (!server || !server.containerId) {
      return res.status(404).json({ error: "Not found" });
    }
    if (!canManageServer(req, server)) return res.status(403).json({ error: "Forbidden" });
    if (server.suspended) return res.status(403).json({ error: "Server is suspended" });
    try {
      const io = req.app.get("io");
      if (io) io.to(`server_${id}`).emit("clear_logs");

      await restartContainer(server.containerId, server.nodeId);
    } catch (startErr: any) {
      if (startErr.statusCode === 404 || (startErr.message && startErr.message.toLowerCase().includes("no such container"))) {
        console.log(`Container missing for server ${server.id}. Recreating...`);
        server.containerId = await createServerContainer(server);
        await writeJSON("servers.json", servers);
        await startContainer(server.containerId, server.nodeId);
      } else {
        throw startErr;
      }
    }
    await attachContainerSocket(server.containerId, server.id, server.nodeId);
    await audit("server.restarted",req,{serverId:id,nodeId:server.nodeId});
    res.json({ success: true });
  } catch (err: any) {
    console.error("Restart server error:", err);
    const failure = nodeOperationError(err, "Failed to restart server");
    res.status(failure.statusCode).json(failure.body);
  }
};

export const sendCommand = async (req: Request, res: Response) => {
  
  try {
    const { id } = req.params;
    const { command } = req.body;
    const servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    if (!server || !server.containerId) {
      return res.status(404).json({ error: "Not found" });
    }
    if (!canManageServer(req, server)) return res.status(403).json({ error: "Forbidden" });
    if (typeof command !== "string" || command.length === 0 || command.length > 4096) return res.status(400).json({ error: "Invalid command" });
    await sendContainerCommand(server.containerId, command, server.nodeId);
    res.json({ success: true });
  } catch (err: any) {
    console.error("Command error:", err);
    res.status(500).json({ error: err.message || "Failed to send command" });
  }
};

export const changeServerVersion = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { version, type, javaVersion } = req.body;
    const user = (req as any).user;
    const normalizedJavaVersion = javaVersion ? String(javaVersion) : "";
    
    if (!version) return res.status(400).json({ error: "Version is required" });
    if (normalizedJavaVersion && !SUPPORTED_JAVA_VERSIONS.includes(normalizedJavaVersion as typeof SUPPORTED_JAVA_VERSIONS[number])) {
      return res.status(400).json({ error: `Unsupported Java version. Choose one of: ${SUPPORTED_JAVA_VERSIONS.join(", ")}` });
    }
    
    let servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    
    if (!server) {
      return res.status(404).json({ error: "Server not found" });
    }

    if (user.role !== "admin" && user.role !== "owner" && server.owner !== user.id) {
      return res.status(403).json({ error: "Only admins or owners can change version" });
    }

    if (server.containerId) {
      const status = await getContainerStatus(server.containerId, server.nodeId);
      if (status?.State?.Running) {
        return res.status(400).json({ error: "Server must be stopped before changing version. Please stop the server first." });
      }
      // Delete old container
      await deleteContainer(server.containerId, server.nodeId);
    }
    
    // Automatically delete config files to avoid issues when switching versions/types
    const serverDir = path.join(process.cwd(), ".data", "servers", id);
    const filesToDelete = [
      "paper-global.yml", "paper-world-defaults.yml", "paper.yml",
      "config/paper-global.yml", "config/paper-world-defaults.yml",
      "world/data/random_sequences.dat"
    ];
    
    for (const file of filesToDelete) {
      const filePath = path.join(serverDir, file);
      try {
        if (await fs.pathExists(filePath)) {
          await fs.remove(filePath);
        }
      } catch (e) {
        console.error(`Failed to delete ${file}`, e);
      }
    }
    
    server.version = version;
    if (type) {
      server.type = type;
    }
    server.javaVersion = normalizedJavaVersion;
    // Recreate container with new version env
    const newContainerId = await createServerContainer(server);
    server.containerId = newContainerId;
    
    await writeJSON("servers.json", servers);
    
    res.json({ success: true, version, type: server.type });
  } catch (err: any) {
    console.error("Change version error", err);
    res.status(500).json({ error: err.message });
  }
};

export const changeJavaVersion = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const requested = String(req.body?.javaVersion || "");
    const user = (req as any).user;
    if (!SUPPORTED_JAVA_VERSIONS.includes(requested as typeof SUPPORTED_JAVA_VERSIONS[number])) {
      return res.status(400).json({ error: `Unsupported Java version. Choose one of: ${SUPPORTED_JAVA_VERSIONS.join(", ")}` });
    }

    const servers = await readJSON("servers.json") || [];
    const server = servers.find((candidate: any) => candidate.id === id);
    if (!server) return res.status(404).json({ error: "Server not found" });
    if (!canManageServer(req, server)) return res.status(403).json({ error: "Only admins, owners, or the server owner can change Java" });
    if (String(server.javaVersion || "") === requested) return res.json({ success: true, javaVersion: requested, unchanged: true });

    if (server.containerId) {
      const status = await getContainerStatus(server.containerId, server.nodeId);
      if (status?.State?.Running) {
        return res.status(400).json({ error: "Server must be stopped before changing Java. Please stop the server first." });
      }
      await deleteContainer(server.containerId, server.nodeId);
    }

    server.javaVersion = requested;
    server.containerId = await createServerContainer(server);
    await writeJSON("servers.json", servers);
    await audit("server.java_version_changed", req, { serverId: id, javaVersion: requested });
    res.json({ success: true, javaVersion: requested, containerId: server.containerId });
  } catch (err: any) {
    console.error("Change Java version error", err);
    res.status(500).json({ error: err.message || "Failed to change Java version" });
  }
};

// File manager basics
export const getFiles = async (req: Request, res: Response) => {
  const { id } = req.params;
  const servers=await readJSON("servers.json")||[]; const server=servers.find((x:any)=>x.id===id); const remote=await remoteForServer(server);
  const dirPath = req.query.path ? String(req.query.path) : "/";
  if(remote){
    try {
      const relativePath = dirPath.replace(/^[/\\\\]+/, "") || ".";
      const isFileRequest = relativePath !== "." && !relativePath.endsWith("/") && Boolean(relativePath.split("/").pop()?.includes("."));
      const data = await nodeControl.files(remote, id, isFileRequest ? "read" : "list", { path: relativePath });
      return res.json(data);
    } catch(e:any){ return res.status(502).json({error:e.message}); }
  }
  await ensureLocalWorkspaceFiles(server);
  const targetPath = resolveServerPath(id, dirPath);
  if (!targetPath) return res.status(403).json({ error: "Invalid path" });

  try {
    const stats = await fs.stat(targetPath).catch(() => null);
    if (!stats) {
      // Return empty if not found
      return res.json([]);
    }
    if (stats.isFile()) {
       const content = await fs.readFile(targetPath, "utf-8");
       return res.json({ isFile: true, content });
    }
    const files = await fs.readdir(targetPath, { withFileTypes: true });
    res.json(files.map(f => ({
      name: f.name,
      isDirectory: f.isDirectory(),
      size: f.isDirectory() ? 0 : fs.statSync(path.join(targetPath, f.name)).size
    })));
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
};

export const uploadFile = async (req: Request, res: Response) => {
  const { id } = req.params;
  const dirPath = String(req.body.path || "/");
  const server = (await readJSON("servers.json") || []).find((x: any) => x.id === id);
  const remote = await remoteForServer(server);
  if (!req.file) return res.status(400).json({ error: "A file is required" });
  try {
    if (remote) {
      const bytes = await fs.readFile(req.file.path);
      const result = await nodeControl.writeBase64(remote, id, path.posix.join(dirPath, req.file.originalname), bytes.toString("base64"));
      return res.json({ success: true, remote: true, ...result });
    }
    const targetPath = resolveServerPath(id, dirPath);
    if (!targetPath) return res.status(403).json({ error: "Invalid path" });
    await fs.ensureDir(targetPath);
    await fs.move(req.file.path, path.join(targetPath, path.basename(req.file.originalname)), { overwrite: true });
    return res.json({ success: true });
  } finally {
    if (await fs.pathExists(req.file.path)) await fs.remove(req.file.path);
  }
};

export const uploadChunk = async (req: Request, res: Response) => {
  const { id } = req.params;
  const uploadId = String(req.body?.uploadId || "");
  const relativePath = String(req.body?.filePath || "");
  const offset = Number(req.body?.offset);
  const totalSize = Number(req.body?.totalSize);
  const content = String(req.body?.content || "");
  if (!/^[a-zA-Z0-9_-]{8,100}$/.test(uploadId) || !relativePath || !Number.isSafeInteger(offset) || offset < 0 || !Number.isSafeInteger(totalSize) || totalSize < 0) return res.status(400).json({ error: "Invalid upload chunk metadata" });
  const chunk = Buffer.from(content, "base64");
  if (chunk.length === 0 || chunk.length > 8 * 1024 * 1024 || offset + chunk.length > totalSize) return res.status(400).json({ error: "Invalid upload chunk size" });
  const server = (await readJSON("servers.json") || []).find((x: any) => x.id === id);
  const remote = await remoteForServer(server);
  try {
    if (remote) return res.json(await nodeControl.writeChunk(remote, id, relativePath, uploadId, offset, totalSize, content));
    const baseDir = serverBasePath(id);
    const target = resolveServerPath(id, relativePath);
    if (!target) return res.status(403).json({ error: "Invalid path" });
    const tempDir = path.join(process.cwd(), ".data", "temp", "uploads", id);
    const temp = path.join(tempDir, `${uploadId}.part`);
    await fs.ensureDir(tempDir);
    const handle = await fs.open(temp, (await fs.pathExists(temp)) ? "r+" : "w+");
    try { await fs.write(handle, chunk, 0, chunk.length, offset); } finally { await fs.close(handle); }
    const nextOffset = offset + chunk.length;
    const complete = nextOffset === totalSize;
    if (complete) { await fs.ensureDir(path.dirname(target)); await fs.move(temp, target, { overwrite: true }); }
    return res.json({ success: true, offset: nextOffset, bytes: chunk.length, complete });
  } catch (e: any) { return res.status(remote ? 502 : 500).json({ error: e.message }); }
};

export const deleteFile = async (req: Request, res: Response) => {
  const { id } = req.params;
  const filePaths = req.body.paths || (req.body.path ? [req.body.path] : []);
  const server=(await readJSON("servers.json")||[]).find((x:any)=>x.id===id); const remote=await remoteForServer(server);
  if(remote){try{return res.json(await nodeControl.files(remote,id,"delete",{paths:filePaths}))}catch(e:any){return res.status(502).json({error:e.message})}}
  
  try {
    for (const filePath of filePaths) {
      const targetPath = resolveServerPath(id, filePath);
      if (!targetPath) return res.status(403).json({ error: "Invalid path" });
      
      await fs.remove(targetPath);
    }
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
};

export const zipFiles = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { dirPath, fileNames, outputName } = req.body;
  const remote = await remoteForServer((req as any).server);
  if (remote) {
    try {
      return res.json(await nodeControl.files(remote, id, "zip", { dirPath, fileNames, outputName }));
    } catch (e: any) {
      return res.status(502).json({ error: e.message || "Remote archive failed" });
    }
  }
  const baseDir = resolveServerPath(id, dirPath);
  const outZipPath = resolveServerPath(id, path.join(String(dirPath || ""), String(outputName || "archive.zip")));
  if (!baseDir || !outZipPath) return res.status(403).json({ error: "Invalid path" });

  try {
    const output = fs.createWriteStream(outZipPath);
    const archive = new ZipArchive({ zlib: { level: 9 } });

    output.on("close", () => {
      res.json({ success: true, filename: outputName || "archive.zip" });
    });

    archive.on("error", (err: any) => {
      console.error("Archive error:", err);
      if (!res.headersSent) res.status(500).json({ error: err.message });
    });

    archive.pipe(output);

    if (!Array.isArray(fileNames)) return res.status(400).json({ error: "fileNames must be an array" });
    for (const name of fileNames) {
      const filePath = resolveServerPath(id, path.join(String(dirPath || ""), String(name)));
      if (!filePath) return res.status(403).json({ error: "Invalid path" });
      const stat = await fs.stat(filePath);
      if (stat.isDirectory()) {
        archive.directory(filePath, name);
      } else {
        archive.file(filePath, { name });
      }
    }

    await archive.finalize();
  } catch (e: any) {
    if (!res.headersSent) res.status(500).json({ error: e.message });
  }
};

export const renameFile = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { oldPath, newPath } = req.body;
  const server=(await readJSON("servers.json")||[]).find((x:any)=>x.id===id); const remote=await remoteForServer(server);
  if(remote){try{return res.json(await nodeControl.files(remote,id,"rename",{oldPath,newPath}))}catch(e:any){return res.status(502).json({error:e.message})}}

  const targetOldPath = resolveServerPath(id, oldPath);
  const targetNewPath = resolveServerPath(id, newPath);
  if (!targetOldPath || !targetNewPath) return res.status(403).json({ error: "Invalid path" });

  try {
    await fs.rename(targetOldPath, targetNewPath);
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
}

export const downloadFile = async (req: Request, res: Response) => {
  const { id } = req.params;
  let rawPaths: string[] = [];
  if (req.query.paths) {
    rawPaths = Array.isArray(req.query.paths) ? (req.query.paths as string[]) : String(req.query.paths).split(",");
  } else if (req.query.path) {
    rawPaths = [String(req.query.path)];
  }

  if (rawPaths.length === 0) {
    return res.status(400).json({ error: "No path specified" });
  }
  const server = (await readJSON("servers.json") || []).find((x: any) => x.id === id);
  const remote = await remoteForServer(server);
  if (remote) {
    try {
      const response: any = await nodeControl.download(remote, id, rawPaths);
      const contentType = response.headers?.["content-type"];
      const contentDisposition = response.headers?.["content-disposition"];
      const contentLength = response.headers?.["content-length"];
      if (contentType) res.setHeader("Content-Type", contentType);
      if (contentDisposition) res.setHeader("Content-Disposition", contentDisposition);
      if (contentLength) res.setHeader("Content-Length", contentLength);
      response.data.pipe(res);
      return;
    } catch (e: any) {
      return res.status(502).json({ error: e.message || "Remote download failed" });
    }
  }
  try {
    if (rawPaths.length === 1) {
      const singlePath = rawPaths[0];
      const targetPath = resolveServerPath(id, singlePath);
      if (!targetPath) return res.status(403).json({ error: "Invalid path" });

      const stat = await fs.stat(targetPath);
      if (!stat.isDirectory()) {
        return res.download(targetPath, path.basename(targetPath));
      }
    }

    // Multiple items OR a single directory -> stream as ZIP
    const zipName = rawPaths.length === 1 
      ? `${path.basename(rawPaths[0]) || "folder"}.zip`
      : `download-${Date.now()}.zip`;

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", `attachment; filename="${zipName}"`);

    const archive = new ZipArchive({ zlib: { level: 9 } });
    archive.on("error", (err: any) => {
      if (!res.headersSent) res.status(500).json({ error: err.message });
    });
    archive.pipe(res);

    for (const relPath of rawPaths) {
      const targetPath = resolveServerPath(id, relPath);
      if (!targetPath) continue;
      const itemName = path.basename(targetPath);
      const stat = await fs.stat(targetPath).catch(() => null);
      if (!stat) continue;

      if (stat.isDirectory()) {
        archive.directory(targetPath, itemName);
      } else {
        archive.file(targetPath, { name: itemName });
      }
    }

    await archive.finalize();
  } catch (e: any) {
    if (!res.headersSent) res.status(500).json({ error: e.message });
  }
};

export const unzipFile = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { path: filePath } = req.body;
  const remote = await remoteForServer((req as any).server);
  if (remote) {
    try {
      return res.json(await nodeControl.files(remote, id, "unzip", { path: filePath }));
    } catch (e: any) {
      return res.status(502).json({ error: e.message || "Remote extraction failed" });
    }
  }
  const targetPath = resolveServerPath(id, filePath);
  if (!targetPath) return res.status(403).json({ error: "Invalid path" });

  try {
    const destDir = path.dirname(targetPath);
    await extract(targetPath, { dir: destDir });
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
};


export const createFile = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { filePath } = req.body;
  const server = (await readJSON("servers.json") || []).find((x: any) => x.id === id);
  const remote = await remoteForServer(server);
  try {
    if (remote) return res.json(await nodeControl.files(remote, id, "write", { path: filePath, content: "" }));
    const targetPath = resolveServerPath(id, filePath);
    if (!targetPath) return res.status(403).json({ error: "Invalid path" });
    await fs.ensureDir(path.dirname(targetPath));
    await fs.writeFile(targetPath, "", "utf-8");
    return res.json({ success: true });
  } catch (e: any) {
    return res.status(remote ? 502 : 500).json({ error: e.message });
  }
};

export const createDirectory = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { filePath } = req.body;
  const server=(await readJSON("servers.json")||[]).find((x:any)=>x.id===id); const remote=await remoteForServer(server);
  if(remote){try{return res.json(await nodeControl.files(remote,id,"mkdir",{path:filePath}))}catch(e:any){return res.status(502).json({error:e.message})}}
  const targetPath = resolveServerPath(id, filePath);
  if (!targetPath) return res.status(403).json({ error: "Invalid path" });
  try {
    await fs.mkdir(targetPath, { recursive: true });
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
};

export const saveFileContent = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { filePath, content } = req.body;
  const server=(await readJSON("servers.json")||[]).find((x:any)=>x.id===id); const remote=await remoteForServer(server);
  if(remote){try{return res.json(await nodeControl.files(remote,id,"write",{path:filePath,content}))}catch(e:any){return res.status(502).json({error:e.message})}}

  const targetPath = resolveServerPath(id, filePath);
  if (!targetPath) return res.status(403).json({ error: "Invalid path" });

  try {
    await fs.writeFile(targetPath, content, "utf-8");
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
}

export const getBackups = async (req: Request, res: Response) => {
  const { id } = req.params;
  const backupsDir = backupBasePath(id);
  await fs.ensureDir(backupsDir);

  try {
    const files = await fs.readdir(backupsDir);
    const backups = [];
    for (const file of files) {
      if (file.endsWith(".zip")) {
        const backupPath = resolveBackupPath(id, file);
        if (!backupPath) continue;
        const stats = await fs.stat(backupPath);
        backups.push({
          filename: file,
          size: stats.size,
          createdAt: stats.birthtime,
        });
      }
    }
    backups.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
    res.json(backups);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
};

export const createBackup = async (req: Request, res: Response) => {
  const { id } = req.params;
  const serverDir = serverBasePath(id);
  const backupsDir = backupBasePath(id);
  await fs.ensureDir(backupsDir);

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const filename = `backup-${timestamp}.zip`;
  const backupPath = path.join(backupsDir, filename);

  try {
    const serverExists = await fs.pathExists(serverDir);
    if (!serverExists) {
       await fs.ensureDir(serverDir); // ensure it acts properly if empty
    }

    const output = fs.createWriteStream(backupPath);
    const archive = new ZipArchive({ zlib: { level: 9 } });

    output.on("close", () => {
      if (!res.headersSent) res.json({ success: true, filename });
    });

    archive.on("error", (err: any) => {
      console.error("Archive error:", err);
      if (!res.headersSent) res.status(500).json({ error: err.message });
    });

    archive.pipe(output);
    archive.directory(serverDir, false);
    await archive.finalize();
  } catch (e: any) {
    if (!res.headersSent) res.status(500).json({ error: e.message });
  }
};

export const downloadBackup = async (req: Request, res: Response) => {
  const { id, filename } = req.params;
  const backupPath = resolveBackupPath(id, filename);
  if (!backupPath) return res.status(403).send("Invalid path");

  if (await fs.pathExists(backupPath)) {
    res.download(backupPath);
  } else {
    res.status(404).send("Backup not found");
  }
};

export const deleteBackup = async (req: Request, res: Response) => {
  const { id, filename } = req.params;
  const backupPath = resolveBackupPath(id, filename);
  if (!backupPath) return res.status(403).json({ error: "Invalid path" });

  try {
    await fs.remove(backupPath);
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
};
const MAX_MARKETPLACE_FILE_BYTES = 80 * 1024 * 1024;
const marketplaceFilename = (value: unknown, fallback: string) => {
  const name = path.basename(String(value || fallback)).replace(/[^a-zA-Z0-9._-]/g, "_");
  if (!name || name === "." || name === ".." || !name.toLowerCase().endsWith(".jar")) return fallback;
  return name;
};
const TRUSTED_MARKETPLACE_HOSTS = new Set(["cdn.modrinth.com", "api.modrinth.com", "api.spiget.org", "hangar.papermc.io", "github.com", "raw.githubusercontent.com", "objects.githubusercontent.com"]);
const downloadMarketplaceBinary = async (url: string) => {
  const parsed = new URL(url);
  if (parsed.protocol !== "https:" || !TRUSTED_MARKETPLACE_HOSTS.has(parsed.hostname)) throw new Error("Marketplace download host is not trusted");
  const response = await axios.get<ArrayBuffer>(parsed.toString(), { responseType: "arraybuffer", timeout: 60_000, maxContentLength: MAX_MARKETPLACE_FILE_BYTES, maxBodyLength: MAX_MARKETPLACE_FILE_BYTES, headers: { "User-Agent": "ShiroNex-Panel/1.0 marketplace" } });
  const bytes = Buffer.from(response.data);
  if (!bytes.length || bytes.length > MAX_MARKETPLACE_FILE_BYTES) throw new Error("Marketplace file is empty or too large");
  return bytes;
};
const resolveModrinthVersion = async (projectId: string, gameVersion?: unknown, loader?: unknown) => {
  const params: Record<string, string> = { include_changelog: "false" };
  const version = typeof gameVersion === "string" ? gameVersion.trim() : "";
  const platform = typeof loader === "string" ? loader.trim().toLowerCase() : "";
  if (version) params.game_versions = JSON.stringify([version]);
  if (platform) params.loaders = JSON.stringify([platform]);
  const response = await axios.get(`https://api.modrinth.com/v2/project/${encodeURIComponent(projectId)}/version`, { params, timeout: 12_000, headers: { "User-Agent": "ShiroNex-Panel/1.0 marketplace" } });
  const versions = Array.isArray(response.data) ? response.data.filter((candidate: any) => Array.isArray(candidate.files) && candidate.files.length > 0) : [];
  versions.sort((left: any, right: any) => {
    const releaseRank = (value: unknown) => value === "release" ? 0 : value === "beta" ? 1 : 2;
    return releaseRank(left.version_type) - releaseRank(right.version_type) || String(right.date_published || "").localeCompare(String(left.date_published || ""));
  });
  const selected = versions[0];
  const file = selected?.files?.find((candidate: any) => candidate.primary) || selected?.files?.[0];
  if (!selected || !file?.url) throw new Error("No compatible downloadable Modrinth version was found");
  return { version: selected, file };
};
const writeMarketplaceBinary = async (req: Request, serverId: string, relativePath: string, bytes: Buffer) => {
  const remote = await remoteForServer((req as any).server);
  if (remote) return nodeControl.writeBase64(remote, serverId, relativePath, bytes.toString("base64"));
  const target = path.join(process.cwd(), ".data", "servers", serverId, relativePath);
  await fs.ensureDir(path.dirname(target));
  await fs.writeFile(target, bytes);
  return { success: true };
};
const safePluginFilename = (value: unknown) => {
  const filename = path.basename(String(value || ""));
  if (!/^[a-zA-Z0-9._-]+\.jar$/i.test(filename)) throw new Error("Invalid plugin filename");
  return filename;
};
export const listInstalledPlugins = async (req: Request, res: Response) => {
  const server = (req as any).server;
  try {
    const remote = await remoteForServer(server);
    if (remote) {
      const entries = await nodeControl.files(remote, server.id, "list", { path: "plugins" });
      return res.json({ items: (Array.isArray(entries) ? entries : []).filter((entry: any) => entry?.isFile && /\.jar$/i.test(String(entry.name))).map((entry: any) => ({ filename: entry.name, size: Number(entry.size) || 0 })) });
    }
    const directory = path.join(process.cwd(), ".data", "servers", server.id, "plugins");
    const entries = await fs.pathExists(directory) ? await fs.readdir(directory, { withFileTypes: true }) : [];
    const items = await Promise.all(entries.filter((entry) => entry.isFile() && /\.jar$/i.test(entry.name)).map(async (entry) => ({ filename: entry.name, size: (await fs.stat(path.join(directory, entry.name))).size })));
    return res.json({ items });
  } catch (error: any) {
    return res.status(502).json({ error: error?.message || "Unable to read installed plugins" });
  }
};
export const removeInstalledPlugin = async (req: Request, res: Response) => {
  const server = (req as any).server;
  try {
    const filename = safePluginFilename(req.params.filename);
    const remote = await remoteForServer(server);
    if (remote) await nodeControl.files(remote, server.id, "delete", { paths: [`plugins/${filename}`] });
    else await fs.remove(path.join(process.cwd(), ".data", "servers", server.id, "plugins", filename));
    return res.json({ success: true, filename });
  } catch (error: any) {
    return res.status(400).json({ error: error?.message || "Unable to remove plugin" });
  }
};
const isSafeRelativeMarketplacePath = (value: unknown) => {
  const normalized = String(value || "").replace(/\\/g, "/");
  return Boolean(normalized) && !normalized.startsWith("/") && !normalized.startsWith("\\") && !/^[A-Za-z]:/.test(normalized) && !normalized.split("/").some((part) => part === ".." || part === "");
};
const verifyMarketplaceHash = (bytes: Buffer, hashes: any) => {
  if (!hashes || typeof hashes !== "object") return;
  if (typeof hashes.sha512 === "string" && crypto.createHash("sha512").update(bytes).digest("hex") !== hashes.sha512.toLowerCase()) throw new Error("Modrinth file SHA-512 verification failed");
  if (typeof hashes.sha1 === "string" && crypto.createHash("sha1").update(bytes).digest("hex") !== hashes.sha1.toLowerCase()) throw new Error("Modrinth file SHA-1 verification failed");
};
const buildMrpackInstallTree = async (archiveRoot: string, outputRoot: string) => {
  const manifestPath = path.join(archiveRoot, "modrinth.index.json");
  if (!(await fs.pathExists(manifestPath))) throw new Error("The .mrpack archive is missing modrinth.index.json");
  const manifest = await fs.readJSON(manifestPath);
  if (manifest?.formatVersion !== 1 || manifest?.game !== "minecraft" || !Array.isArray(manifest.files)) throw new Error("Unsupported or invalid Modrinth pack manifest");
  await fs.ensureDir(outputRoot);
  let totalBytes = 0;
  for (const entry of manifest.files) {
    const relativePath = String(entry?.path || "").replace(/\\/g, "/");
    if (!isSafeRelativeMarketplacePath(relativePath)) throw new Error("Modrinth manifest contains an unsafe file path");
    if (entry?.env?.server === "unsupported") continue;
    const downloads = Array.isArray(entry?.downloads) ? entry.downloads.filter((value: unknown) => typeof value === "string") : [];
    const url = downloads[0] || "";
    if (!url) throw new Error(`Modrinth manifest has no download URL for ${relativePath}`);
    const bytes = await downloadMarketplaceBinary(url);
    totalBytes += bytes.length;
    if (totalBytes > 512 * 1024 * 1024) throw new Error("Modrinth pack dependencies exceed the 512 MB safety limit");
    verifyMarketplaceHash(bytes, entry.hashes);
    const target = path.join(outputRoot, relativePath);
    await fs.ensureDir(path.dirname(target));
    await fs.writeFile(target, bytes);
  }
  for (const override of ["overrides", "server-overrides"]) {
    const overridePath = path.join(archiveRoot, override);
    if (await fs.pathExists(overridePath)) await copyDirectorySafely(overridePath, outputRoot);
  }
  const dependencies = manifest.dependencies && typeof manifest.dependencies === "object" ? manifest.dependencies : {};
  const runtimeType = dependencies["fabric-loader"] ? "FABRIC" : dependencies.forge ? "FORGE" : dependencies.neoforge ? "NEOFORGE" : dependencies["quilt-loader"] ? "QUILT" : null;
  return { name: String(manifest.name || "Modrinth pack"), files: totalBytes, runtimeType, minecraftVersion: typeof dependencies.minecraft === "string" ? dependencies.minecraft : null };
};
const persistDetectedMrpackRuntime = async (serverId: string, detected: { runtimeType: string | null; minecraftVersion: string | null }) => {
  if (!detected.runtimeType && !detected.minecraftVersion) return;
  const servers = await readJSON("servers.json") || [];
  const server = servers.find((candidate: any) => candidate.id === serverId);
  if (!server) return;
  if (detected.runtimeType) server.type = detected.runtimeType;
  if (detected.minecraftVersion) server.version = detected.minecraftVersion;
  server.runtimeDetectedAt = new Date().toISOString();
  await writeJSON("servers.json", servers);
};
const collectArchiveFiles = async (root: string, current = ""): Promise<Array<{ path: string; content: string }>> => {
  const directory = path.join(root, current);
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files: Array<{ path: string; content: string }> = [];
  for (const entry of entries) {
    const rel = path.posix.join(current.split(path.sep).join("/"), entry.name);
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collectArchiveFiles(root, path.join(current, entry.name)));
    else if (entry.isFile() && entry.name !== "modrinth.index.json") {
      const bytes = await fs.readFile(absolute);
      files.push({ path: rel, content: bytes.toString("base64") });
    }
  }
  return files;
};

export const installPlugin = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { source, pluginId, pluginName, gameVersion, loader } = req.body;
  const server = (req as any).server || {};
  const effectiveGameVersion = typeof gameVersion === "string" && gameVersion.trim() ? gameVersion.trim() : String(server.version || "").trim();
  const effectiveLoader = typeof loader === "string" && loader.trim() ? loader.trim() : String(server.type || "").trim().toLowerCase();
  
  // Allow direct downloadUrl fallback for backward compatibility
  if (req.body.downloadUrl) {
    try {
      const filename = marketplaceFilename(req.body.filename, "plugin.jar");
      const bytes = await downloadMarketplaceBinary(String(req.body.downloadUrl));
      await writeMarketplaceBinary(req, id, `plugins/${filename}`, bytes);
      return res.json({ success: true, message: "Plugin installed successfully" });
    } catch (e: any) {
      return res.status(502).json({ error: e?.message || "Failed to install plugin" });
    }
  }

  if (!source || !pluginId || !pluginName) {
    return res.status(400).json({ error: "Missing source, pluginId, or pluginName" });
  }

  try {
    const serverDir = path.join(process.cwd(), ".data", "servers", id);
    const pluginsDir = path.join(serverDir, "plugins");
    await fs.ensureDir(pluginsDir);
    
    let downloadUrl = null;
    let filename = `${pluginName.replace(/[^a-zA-Z0-9]/g, '_')}.jar`;
    const axios = (await import("axios")).default;

    const resolveGithubRelease = async (extUrl: string) => {
      if (extUrl.includes('github.com') && extUrl.includes('/releases/')) {
        let apiUrl = null;
        const match = extUrl.match(/github\.com\/([^\/]+)\/([^\/]+)\/releases\/tag\/([^\/]+)/);
        if (match) {
          apiUrl = `https://api.github.com/repos/${match[1]}/${match[2]}/releases/tags/${match[3]}`;
        } else {
          const matchLatest = extUrl.match(/github\.com\/([^\/]+)\/([^\/]+)\/releases\/latest/);
          if (matchLatest) {
            apiUrl = `https://api.github.com/repos/${matchLatest[1]}/${matchLatest[2]}/releases/latest`;
          }
        }
        if (apiUrl) {
          try {
            const ghRes = await axios.get(apiUrl);
            if (ghRes.data && ghRes.data.assets) {
              const jarAsset = ghRes.data.assets.find((a: any) => a.name.endsWith('.jar'));
              if (jarAsset) {
                return { url: jarAsset.browser_download_url, filename: jarAsset.name };
              }
            }
          } catch(e) {
            console.error('GitHub API error:', e);
          }
        }
      }
      return null;
    };

    if (source === 'modrinth') {
      const resolved = await resolveModrinthVersion(pluginId, effectiveGameVersion, effectiveLoader);
      downloadUrl = resolved.file.url;
      filename = resolved.file.filename || filename;
    } else if (source === 'spiget' || source === 'spigot') {
       const apiRes = await axios.get(`https://api.spiget.org/v2/resources/${pluginId}`);
       if (apiRes.data && apiRes.data.file) {
         if (apiRes.data.file.type === 'external' && apiRes.data.file.externalUrl) {
           const extUrl = apiRes.data.file.externalUrl;
           const ghAsset = await resolveGithubRelease(extUrl);
           if (ghAsset) {
             downloadUrl = ghAsset.url;
             filename = ghAsset.filename;
           }
           if (!downloadUrl) {
             return res.status(400).json({ error: "This plugin must be downloaded externally from: " + extUrl });
           }
         } else {
           downloadUrl = `https://api.spiget.org/v2/resources/${pluginId}/download`;
         }
       } else {
         downloadUrl = `https://api.spiget.org/v2/resources/${pluginId}/download`;
       }
    } else if (source === 'hangar') {
       const [owner, slug] = pluginId.split('/');
       const verRes = await axios.get(`https://hangar.papermc.io/api/v1/projects/${owner}/${slug}/versions`);
       if (verRes.data && verRes.data.result && verRes.data.result.length > 0) {
         const version = verRes.data.result[0];
         const download = version.downloads.PAPER || Object.values(version.downloads)[0];
         if (download && (download as any).downloadUrl) {
            downloadUrl = (download as any).downloadUrl;
            if ((download as any).fileInfo && (download as any).fileInfo.name) {
                filename = (download as any).fileInfo.name;
            }
         } else if (download && (download as any).externalUrl) {
            const extUrl = (download as any).externalUrl;
            const ghAsset = await resolveGithubRelease(extUrl);
            if (ghAsset) {
              downloadUrl = ghAsset.url;
              filename = ghAsset.filename;
            } else {
              return res.status(400).json({ error: "This plugin must be downloaded externally from: " + extUrl });
            }
         }
       }
    }

    if (!downloadUrl) {
      return res.status(404).json({ error: "Could not find a valid download URL for this plugin." });
    }

    const bytes = await downloadMarketplaceBinary(String(downloadUrl));
    await writeMarketplaceBinary(req, id, `plugins/${marketplaceFilename(filename, "plugin.jar")}`, bytes);

    res.json({ success: true, message: "Plugin installed successfully" });
  } catch (error: any) {
    console.error("Plugin installation failed:", error.message);
    res.status(500).json({ error: "Plugin installation failed: " + error.message });
  }
};

export const installMod = async (req: Request, res: Response) => {
  const { id } = req.params;
  const { pluginId, pluginName, gameVersion, loader } = req.body;
  const server = (req as any).server || {};
  const effectiveGameVersion = typeof gameVersion === "string" && gameVersion.trim() ? gameVersion.trim() : String(server.version || "").trim();
  const effectiveLoader = typeof loader === "string" && loader.trim() ? loader.trim() : String(server.type || "").trim().toLowerCase();

  if (!pluginId || !pluginName) {
    return res.status(400).json({ error: "Missing pluginId or pluginName" });
  }

  try {
    let downloadUrl = null;
    let filename = marketplaceFilename(`${pluginName.replace(/[^a-zA-Z0-9]/g, '_')}.jar`, "mod.jar");
    const axios = (await import("axios")).default;

    const resolved = await resolveModrinthVersion(pluginId, effectiveGameVersion, effectiveLoader);
    if (resolved?.file) {
      downloadUrl = resolved.file.url;
      filename = marketplaceFilename(resolved.file.filename, filename);
    }

    if (!downloadUrl) {
      return res.status(404).json({ error: "Could not find a valid download URL for this mod." });
    }

    const bytes = await downloadMarketplaceBinary(String(downloadUrl));
    await writeMarketplaceBinary(req, id, `mods/${marketplaceFilename(filename, "mod.jar")}`, bytes);

    res.json({ success: true, message: "Mod installed successfully" });
  } catch (error: any) {
    console.error("Mod installation failed:", error.message);
    res.status(500).json({ error: "Mod installation failed: " + error.message });
  }
};

export const updateResources = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { ram, cpu, disk } = req.body;
    const servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    if (!server) return res.status(404).json({ error: "Server not found" });
    if (!canManageServer(req, server)) return res.status(403).json({ error: "Unauthorized" });

    server.ram = Number(ram);
    server.cpu = Number(cpu);
    server.disk = Number(disk);
    await writeJSON("servers.json", servers);

    // Stop container if running
    if (server.containerId) {
       try {
         await stopContainer(server.containerId, server.nodeId);
       } catch(e) {}
    }

    res.json(server);
  } catch (error) {
    res.status(500).json({ error: "Failed to update resources" });
  }
};

export const updateSuspend = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { suspendDuration } = req.body; // permanent, 1_month, 2_months, 24_hours, 1_week, or null
    const servers = await readJSON("servers.json") || [];
    const server = servers.find((s: any) => s.id === id);
    if (!server) return res.status(404).json({ error: "Server not found" });
    if (!canManageServer(req, server)) return res.status(403).json({ error: "Unauthorized" });

    server.suspended = suspendDuration !== null;
    server.suspendDuration = suspendDuration;
    await writeJSON("servers.json", servers);

    if (server.suspended && server.containerId) {
       try {
         await stopContainer(server.containerId, server.nodeId);
       } catch(e) {}
    }

    res.json(server);
  } catch (error) {
    res.status(500).json({ error: "Failed to suspend server" });
  }
};


export const installModpackFromMarketplace = async (req: Request, res: Response) => {
  const { provider, projectId, gameVersion, loader } = req.body || {};
  const server = (req as any).server || {};
  const effectiveGameVersion = typeof gameVersion === "string" && gameVersion.trim() ? gameVersion.trim() : String(server.version || "").trim();
  const effectiveLoader = typeof loader === "string" && loader.trim() ? loader.trim() : String(server.type || "").trim().toLowerCase();
  if (provider !== "modrinth") return res.status(400).json({ error: "Only the official Modrinth modpack provider is supported for remote imports" });
  if (typeof projectId !== "string" || !/^[a-zA-Z0-9_-]{2,80}$/.test(projectId)) {
    return res.status(400).json({ error: "Invalid modpack project id" });
  }
  if (!canManageServer(req, (req as any).server)) return res.status(403).json({ error: "Unauthorized" });

  const tempDir = path.join(process.cwd(), ".data", "temp");
  const tempPath = path.join(tempDir, `marketplace-${crypto.randomUUID()}.mrpack`);
  try {
    await fs.ensureDir(tempDir);
    const resolved = await resolveModrinthVersion(projectId, effectiveGameVersion, effectiveLoader);
    const file = resolved.file;
    const downloadUrl = typeof file.url === "string" ? file.url : "";
    if (!downloadUrl || !downloadUrl.startsWith("https://cdn.modrinth.com/") || !String(file.filename || "").toLowerCase().endsWith(".mrpack")) {
      return res.status(404).json({ error: "No safe compatible Modrinth .mrpack archive was found" });
    }

    const response = await axios.get(downloadUrl, {
      responseType: "stream",
      timeout: 60_000,
      maxContentLength: 512 * 1024 * 1024,
      maxBodyLength: 512 * 1024 * 1024,
      headers: { "User-Agent": "ShiroNex-Panel/1.0 modpack-import" },
    });
    const output = fs.createWriteStream(tempPath);
    response.data.pipe(output);
    await new Promise<void>((resolve, reject) => {
      output.on("finish", resolve);
      output.on("error", reject);
      response.data.on("error", reject);
    });

    (req as any).file = {
      path: tempPath,
      originalname: path.basename(typeof file?.filename === "string" ? file.filename : `${projectId}.mrpack`),
    };
    return importModpack(req, res);
  } catch (error: any) {
    await fs.remove(tempPath).catch(() => undefined);
    if (error?.response?.status === 404) return res.status(404).json({ error: "Modpack project or version not found" });
    res.status(502).json({ error: "Could not download the modpack from Modrinth" });
  }
};

export const importModpack = async (req: Request, res: Response) => {
  const { id } = req.params;
  const uploaded = (req as any).file as { path?: string; originalname?: string } | undefined;
  if (!uploaded?.path) return res.status(400).json({ error: "A .zip or .mrpack archive is required" });
  if (!canManageServer(req, (req as any).server)) return res.status(403).json({ error: "Unauthorized" });

  const originalName = String(uploaded.originalname || "").toLowerCase();
  if (!originalName.endsWith(".zip") && !originalName.endsWith(".mrpack")) {
    await fs.remove(uploaded.path);
    return res.status(400).json({ error: "Only .zip and .mrpack archives are supported" });
  }

  const remote = await remoteForServer((req as any).server);
  const serverDir = path.join(process.cwd(), ".data", "servers", id);
  const backupsDir = path.join(process.cwd(), ".data", "backups", id);
  const tempDir = path.join(process.cwd(), ".data", "temp", `modpack-${crypto.randomUUID()}`);
  const confirmReplace = req.body?.confirmReplace === true || req.body?.confirmReplace === "true";

  try {
    await fs.ensureDir(tempDir);
    const existing = remote ? [] : await fs.readdir(serverDir);
    if (existing.length > 0 && !confirmReplace) {
      await fs.remove(uploaded.path).catch(() => undefined);
      await fs.remove(tempDir).catch(() => undefined);
      return res.status(409).json({ error: "This server already contains files. Create a backup and confirm replacement before importing.", requiresConfirmation: true });
    }

    let backupFilename: string | null = null;
    if (existing.length > 0) {
      await fs.ensureDir(backupsDir);
      backupFilename = `pre-modpack-${new Date().toISOString().replace(/[:.]/g, "-")}.zip`;
      const backupPath = path.join(backupsDir, backupFilename);
      const output = fs.createWriteStream(backupPath);
      const archive = new ZipArchive({ zlib: { level: 9 } });
      archive.pipe(output);
      archive.directory(serverDir, false);
      await archive.finalize();
      await new Promise<void>((resolve, reject) => { output.on("close", () => resolve()); output.on("error", reject); });
    }

    const entries = await extractZipSafely(uploaded.path, tempDir);
    const isMrpack = originalName.endsWith(".mrpack");
    let sourcePath = tempDir;
    let detectedRuntime: { runtimeType: string | null; minecraftVersion: string | null } = { runtimeType: null, minecraftVersion: null };
    if (isMrpack) {
      sourcePath = path.join(tempDir, "compiled");
      detectedRuntime = await buildMrpackInstallTree(tempDir, sourcePath);
    } else {
      const overridesPath = path.join(tempDir, "overrides");
      sourcePath = await fs.pathExists(overridesPath) ? overridesPath : tempDir;
    }
    if (remote) {
      const files = await collectArchiveFiles(sourcePath);
      try {
        await nodeControl.replaceBatch(remote, id, files, confirmReplace);
      } catch (error: any) {
        if (error?.response?.status === 409) {
          await fs.remove(uploaded.path).catch(() => undefined);
          await fs.remove(tempDir).catch(() => undefined);
          return res.status(409).json(error.response.data);
        }
        throw error;
      }
      await persistDetectedMrpackRuntime(id, detectedRuntime);
      await fs.remove(uploaded.path);
      await fs.remove(tempDir);
      return res.json({ success: true, entries: files.length, backupFilename: null, detectedRuntime, message: isMrpack ? "Modrinth pack dependencies were verified and imported on the remote node. Runtime settings were detected from the manifest." : "Archive validated and imported on the remote node. Review the files before starting." });
    }
    await copyDirectorySafely(sourcePath, serverDir);
    const installedEntries = isMrpack ? (await collectArchiveFiles(sourcePath)).length : entries.length;
    await persistDetectedMrpackRuntime(id, detectedRuntime);
    await fs.remove(uploaded.path);
    await fs.remove(tempDir);
    res.json({ success: true, entries: installedEntries, backupFilename, detectedRuntime, message: isMrpack ? "Modrinth pack dependencies were verified and imported. Runtime settings were detected from the manifest." : "Archive validated and imported. Review the files before starting." });
  } catch (error: any) {
    await fs.remove(uploaded.path).catch(() => undefined);
    await fs.remove(tempDir).catch(() => undefined);
    res.status(400).json({ error: error?.message || "Modpack import failed" });
  }
};
